src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
class Order
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createAt = null;

    #[ORM\Column]
    private ?int $state = null;

    #[ORM\Column(length: 255)]
    private ?string $carrier_name = null;

    #[ORM\Column]
    private ?float $carrier_price = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $delivery = null;

    /**
     * @var Collection<int, OrderDetail>
     */
    #[ORM\OneToMany(targetEntity: OrderDetail::class, mappedBy: 'myOrder')]
    private Collection $orderDetails;

    /**
     * @var Collection<int, OrderDetail>
     */
    #[ORM\OneToMany(targetEntity: OrderDetail::class, mappedBy: 'myOrder')]
    private Collection $ordersDetails;

    public function __construct()
    {
        $this->orderDetails = new ArrayCollection();
        $this->ordersDetails = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->createAt;
    }

    public function setCreateAt(\DateTimeInterface $createAt): static
    {
        $this->createAt = $createAt;

        return $this;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getState(): ?int
    {
        return $this->state;
    }

    public function setState(int $state): static
    {
        $this->state = $state;

        return $this;
    }

    public function getCarrierName(): ?string
    {
        return $this->carrier_name;
    }

    public function setCarrierName(string $carrier_name): static
    {
        $this->carrier_name = $carrier_name;

        return $this;
    }

    public function getCarrierPrice(): ?float
    {
        return $this->carrier_price;
    }

    public function setCarrierPrice(float $carrier_price): static
    {
        $this->carrier_price = $carrier_price;

        return $this;
    }

    public function getDelivery(): ?string
    {
        return $this->delivery;
    }

    public function setDelivery(string $delivery): static
    {
        $this->delivery = $delivery;

        return $this;
    }

    /**
     * @return Collection<int, OrderDetail>
     */
    public function getOrderDetails(): Collection
    {
        return $this->orderDetails;
    }

    public function addOrderDetail(OrderDetail $orderDetail): static
    {
        if (!$this->orderDetails->contains($orderDetail)) {
            $this->orderDetails->add($orderDetail);
            $orderDetail->setMyOrder($this);
        }

        return $this;
    }

    public function removeOrderDetail(OrderDetail $orderDetail): static
    {
        if ($this->orderDetails->removeElement($orderDetail)) {
            // set the owning side to null (unless already changed)
            if ($orderDetail->getMyOrder() === $this) {
                $orderDetail->setMyOrder(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, OrderDetail>
     */
    public function getOrdersDetails(): Collection
    {
        return $this->ordersDetails;
    }

    public function addOrdersDetail(OrderDetail $ordersDetail): static
    {
        if (!$this->ordersDetails->contains($ordersDetail)) {
            $this->ordersDetails->add($ordersDetail);
            $ordersDetail->setMyOrder($this);
        }

        return $this;
    }

    public function removeOrdersDetail(OrderDetail $ordersDetail): static
    {
        if ($this->ordersDetails->removeElement($ordersDetail)) {
            // set the owning side to null (unless already changed)
            if ($ordersDetail->getMyOrder() === $this) {
                $ordersDetail->setMyOrder(null);
            }
        }

        return $this;
    }
}

src/Controller/OrderCrudControlleController.php
<?php

namespace App\Controller;

use App\Entity\Order;
use App\Form\Order1Type;
use App\Repository\OrderRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/order/crud/controlle')]
final class OrderCrudControlleController extends AbstractController
{
    #[Route(name: 'app_order_crud_controlle_index', methods: ['GET'])]
    public function index(OrderRepository $orderRepository): Response
    {
        return $this->render('order_crud_controlle/index.html.twig', [
            'orders' => $orderRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_order_crud_controlle_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $order = new Order();
        $form = $this->createForm(Order1Type::class, $order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($order);
            $entityManager->flush();

            return $this->redirectToRoute('app_order_crud_controlle_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('order_crud_controlle/new.html.twig', [
            'order' => $order,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_order_crud_controlle_show', methods: ['GET'])]
    public function show(Order $order): Response
    {
        return $this->render('order_crud_controlle/show.html.twig', [
            'order' => $order,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_order_crud_controlle_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Order $order, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(Order1Type::class, $order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_order_crud_controlle_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('order_crud_controlle/edit.html.twig', [
            'order' => $order,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_order_crud_controlle_delete', methods: ['POST'])]
    public function delete(Request $request, Order $order, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$order->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($order);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_order_crud_controlle_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/order_crud_controlle/_delete_form.html.twig
<form method="post" action="{{ path('app_order_crud_controlle_delete', {'id': order.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ order.id) }}">
    <button class="btn">Delete</button>
</form>

templates/order_crud_controlle/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/order_crud_controlle/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Order{% endblock %}

{% block body %}
    <h1>Edit Order</h1>

    {{ include('order_crud_controlle/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_order_crud_controlle_index') }}">back to list</a>

    {{ include('order_crud_controlle/_delete_form.html.twig') }}
{% endblock %}

templates/order_crud_controlle/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Order index{% endblock %}

{% block body %}
    <h1>Order index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>CreateAt</th>
                <th>State</th>
                <th>Carrier_name</th>
                <th>Carrier_price</th>
                <th>Delivery</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for order in orders %}
            <tr>
                <td>{{ order.id }}</td>
                <td>{{ order.createAt ? order.createAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ order.state }}</td>
                <td>{{ order.carrierName }}</td>
                <td>{{ order.carrierPrice }}</td>
                <td>{{ order.delivery }}</td>
                <td>
                    <a href="{{ path('app_order_crud_controlle_show', {'id': order.id}) }}">show</a>
                    <a href="{{ path('app_order_crud_controlle_edit', {'id': order.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_order_crud_controlle_new') }}">Create new</a>
{% endblock %}

templates/order_crud_controlle/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Order{% endblock %}

{% block body %}
    <h1>Create new Order</h1>

    {{ include('order_crud_controlle/_form.html.twig') }}

    <a href="{{ path('app_order_crud_controlle_index') }}">back to list</a>
{% endblock %}

templates/order_crud_controlle/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Order{% endblock %}

{% block body %}
    <h1>Order</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ order.id }}</td>
            </tr>
            <tr>
                <th>CreateAt</th>
                <td>{{ order.createAt ? order.createAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>State</th>
                <td>{{ order.state }}</td>
            </tr>
            <tr>
                <th>Carrier_name</th>
                <td>{{ order.carrierName }}</td>
            </tr>
            <tr>
                <th>Carrier_price</th>
                <td>{{ order.carrierPrice }}</td>
            </tr>
            <tr>
                <th>Delivery</th>
                <td>{{ order.delivery }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_order_crud_controlle_index') }}">back to list</a>

    <a href="{{ path('app_order_crud_controlle_edit', {'id': order.id}) }}">edit</a>

    {{ include('order_crud_controlle/_delete_form.html.twig') }}
{% endblock %}